import type { Project } from "../../interfaces";
import type { PageLoad } from "./$types";

const projects: Project[] = [
  { name: "VilStats", description: "", stack: ["JavaScript", "PHP", "jQuery", "HTML", "CSS"], isClosed: true },
  {
    name: "GTAV",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "Svelte",
      "TailwindCSS",
      "Vite",
      "daisyUI",
      "AWS S3",
      "discord.js",
      "Express",
      "PostgreSQL",
      "TypeORM",
      "CapRover CI/CD",
    ],
    isClosed: true,
  },
  {
    name: "JeelangaMusic",
    description: "",
    stack: ["JavaScript", "discord.js", "Express", "FFmpeg", "CapRover CI/CD"],
    isClosed: true,
    github: "https://github.com/LWJerri/JeelangaMusic",
  },
  {
    name: "Sreality",
    description: "",
    stack: ["TypeScript", "Docker", "React", "TailwindCSS", "PostgreSQL", "Prisma", "Fastify"],
    isClosed: true,
    github: "https://github.com/LWJerri/Sreality",
  },
  {
    name: "Riddea",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "Husky",
      "Svelte",
      "Vite",
      "CSS",
      "AWS S3",
      "Fastify",
      "PostgreSQL",
      "TypeORM",
      "telegraf.js",
      "NestJS Microservice",
      "GitHub Workflows CI/CD",
    ],
    isClosed: true,
    github: "https://github.com/LWJerri/Riddea",
  },
  {
    name: "AllStarz",
    description: "",
    stack: ["TypeScript", "Docker", "discord.js", "PostgreSQL", "TypeORM", "Stripe", "CapRover CI/CD"],
    isClosed: true,
  },
  { name: "Openner", description: "", stack: ["JavaScript", "discord.js"], isClosed: true },
  {
    name: "telegraf-rate-limiter",
    description: "",
    stack: ["TypeScript", "npmjs", "GitHub Workflows", "telegraf.js"],
    isClosed: true,
    github: "https://github.com/LWJerri/telegraf-rate-limiter",
  },
  {
    name: "MagnifyAI",
    description: "",
    stack: ["TypeScript", "Docker", "BullMQ", "Prisma", "MongoDB", "grammY", "Redis", "bill_line"],
    isClosed: true,
  },
  {
    name: "api.lwjerri.dev",
    description: "",
    stack: ["TypeScript", "Docker", "Fastify", "Prisma", "PostgreSQL", "CapRover CI/CD"],
    isClosed: true,
    github: "https://github.com/LWJerri/api.lwjerri.dev",
  },
  {
    name: "Modestal",
    description: "",
    stack: ["TypeScript", "Docker", "discord.js", "TypeORM", "PostgreSQL", "Redis", "CapRover CI/CD"],
    isClosed: true,
  },
  {
    name: "lwjerri.github.io",
    description: "",
    stack: ["TypeScript", "GitHub Pages", "Svelte", "Vite", "CSS"],
    isClosed: true,
    github: "https://github.com/LWJerri/lwjerri.github.io",
  },
  {
    name: "PoruchBot",
    description: "",
    stack: ["TypeScript", "Docker", "grammY", "Prisma", "PostgreSQL", "BullMQ", "Redis", "CapRover CI/CD"],
    isClosed: true,
  },
  {
    name: "RconOnlineNotifier",
    description: "",
    stack: ["TypeScript", "Docker", "Rcon", "CapRover CI/CD"],
    isClosed: true,
    github: "https://github.com/LWJerri/RconOnlineNotifier",
  },
  {
    name: "jj",
    description: "",
    stack: ["TypeScript", "Docker", "Next", "React", "TailwindCSS", "daisyUI", "MongoDB", "NestJS"],
    isClosed: true,
    github: "https://github.com/LWJerri/jj",
  },
  {
    name: "UserBot",
    description: "",
    stack: ["TypeScript", "Docker", "Prisma", "PostgreSQL", "gramJS", "CapRover CI/CD"],
    isClosed: true,
  },
  {
    name: "React-App",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "OpenAPI",
      "React",
      "TailwindCSS",
      "Zustand",
      "Vite",
      "shadcn/ui",
      "NestJS",
      "Prisma",
      "PostgreSQL",
      "GitHub Actions CI/CD",
    ],
    isClosed: true,
    github: "https://github.com/LWJerri/React-App",
  },
  {
    name: "FindID",
    description: "",
    stack: ["TypeScript", "shadcn/ui", "React", "Tauri", "TailwindCSS", "Vite", "GitHub Actions"],
    isClosed: true,
    github: "https://github.com/LWJerri/FindID",
  },
  {
    name: "React-App-2",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "OpenAPI",
      "React",
      "shadcn/ui",
      "TailwindCSS",
      "Zustand",
      "Storybook",
      "Vite",
      "NestJS",
      "Prisma",
      "PostgreSQL",
      "Jest",
      "GitHub Actions CI/CD",
    ],
    isClosed: true,
    github: "https://github.com/LWJerri/React-App-2",
  },
  {
    name: "TimetableAssistantDUIKT",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "grammY",
      "BullMQ",
      "Redis",
      "Prisma",
      "PostgreSQL",
      "NestJS",
      "JSDom",
      "CapRover CI/CD",
    ],
    isClosed: false,
  },
  {
    name: "CSharpBoard",
    description: "",
    stack: [
      "TypeScript",
      "C#",
      "OpenAPI",
      "React",
      "Zustand",
      "TailwindCSS",
      "Vite",
      "PostgreSQL",
      "NET 8.0",
      "Npgsql",
      "GitHub Actions CI/CD",
    ],
    isClosed: true,
    github: "https://github.com/LWJerri/CSharpBoard",
  },
  {
    name: "SimonBot",
    description: "",
    stack: ["TypeScript", "Docker", "Prisma", "PostgreSQL", "discord.js", "JSDom", "CapRover CI/CD"],
    isClosed: false,
  },
  {
    name: "Lequille",
    description: "",
    stack: ["TypeScript", "Docker", "discord.js", "Prisma", "MongoDB", "CapRover CI/CD"],
    isClosed: true,
  },
  {
    name: "MyStorage",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "Svelte",
      "TailwindCSS",
      "Vite",
      "daisyUI",
      "Fastify",
      "Prisma",
      "PostgreSQL",
      "AWS S3",
      "CapRover CI/CD",
    ],
    isClosed: false,
    github: "https://github.com/LWJerri/MyStorage",
  },
  {
    name: "LWJENNI",
    description: "",
    stack: ["TypeScript", "Docker", "Prisma", "PostgreSQL", "discord.js", "CapRover CI/CD"],
    isClosed: false,
  },
  {
    name: "Pauperial",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "Svelte",
      "TailwindCSS",
      "Vite",
      "daisyUI",
      "TypeORM",
      "PostgreSQL",
      "Express",
      "CapRover CI/CD",
    ],
    isClosed: false,
    github: "https://github.com/LWJerri/Pauperial",
  },
  {
    name: "LoonaSoftBot",
    description: "",
    stack: ["TypeScript", "Docker", "Stripe", "grammY", "Prisma", "PostgreSQL", "Redis", "CapRover CI/CD"],
    isClosed: true,
  },
  {
    name: "dogttpbot",
    description: "",
    stack: ["TypeScript", "Vercel", "grammY", "Express", "ngrok"],
    isClosed: false,
    github: "https://github.com/LWJerri/dogttpbot",
    urls: ["https://t.me/dogttpbot"],
  },
  {
    name: "novaosvita.net",
    description: "",
    stack: ["TypeScript", "Flowbite", "Vue", "TailwindCSS", "Vite", "Portmone"],
    isClosed: true,
  },
  {
    name: "lwjerri.dev",
    description: "",
    stack: ["TypeScript", "Vercel", "Umami", "PDFkit", "SvelteKit", "TailwindCSS", "Vite"],
    isClosed: false,
    github: "https://github.com/LWJerri/lwjerri.dev",
    urls: ["https://lwjerri.dev"],
  },
  {
    name: "ManageGift",
    description: "",
    stack: ["JavaScript", "MongoDB", "Express", "discord.js", "PHP", "HTML", "CSS", "GitHub Actions CI/CD"],
    isClosed: true,
  },
  {
    name: "doctoo",
    description: "",
    stack: [
      "TypeScript",
      "Docker",
      "GCP",
      "NestJS Microservice",
      "NestJS",
      "RabbitMQ",
      "Jest",
      "Stripe",
      "OpenAPI",
      "React",
      "Storybook",
      "Chromatic",
      "JSDom",
      "TailwindCSS",
      "Vite",
      "Vitest",
      "ReDoc",
      "Nodemailer",
      "Redis",
      "PostgreSQL",
      "Prisma",
      "Tesseract",
      "Minio",
      "Angular",
      "Google S3",
      "Karma",
      "GitHub Actions CI/CD",
      "OpenAI",
    ],
    isClosed: true,
  },
];

projects.sort((a, b) => {
  if (a.isClosed !== b.isClosed) return a.isClosed ? 1 : -1;

  return a.name.localeCompare(b.name);
});

export const load = (() => {
  return { projects };
}) satisfies PageLoad;
